services:
  frontend:
    build:
      context: ./Frontend
      args:
        NEXT_PUBLIC_WS_HOST: ${NEXT_PUBLIC_WS_HOST}
        NEXT_PUBLIC_WS_PORT: ${NEXT_PUBLIC_WS_PORT}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - /app/.next
      - /app/node_modules
      - ssl-certs:/etc/nginx/ssl:ro
    env_file:
      - .env

  backend:
    build:
      context: ./Backend
    env_file:
      - .env
    expose:
      - "8001"
    networks:
      - app-network
    volumes:
      - back-data:/app
    depends_on:
      - db

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    volumes:
      - ssl-certs:/etc/nginx/ssl

networks:
  app-network:
    driver: bridge

volumes:
  ssl-certs:
  db-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./Volume/postgresql"
  front-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./Frontend"
  back-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./Backend"
